export type Locale = "zh" | "en";
export const zh = {
  "nav.ecosystem": "产品生态",
  "nav.connection": "协同之力",
  "nav.about": "我们的理念",
  "nav.explore": "探索生态",
  "nav.language": "选择语言",
  "nav.menu": "打开导航",
  "nav.close": "关闭",
  "nav.skip": "跳到主要内容",
  "hero.eyebrow": "为智能而构建 · 为价值而连接",
  "hero.description":
    "让智能成为行动，让连接创造价值。\n七个独立产品，一个持续进化的开放生态。",
  "hero.cta": "探索产品宇宙",
  "hero.secondary": "了解我们的理念",
  "hero.coordinate": "智能 × 协作 × 价值",
  "hero.scroll": "向下探索",
  "hero.art": "缓慢旋转的银绿色环形粒子雕塑，象征产品之间的连接",
  "hero.pause": "暂停动态效果",
  "hero.play": "播放动态效果",
  "hero.caption": "独立运行，彼此连接。",
  "products.eyebrow": "01 / 产品生态",
  "products.title": "各自强大。",
  "products.title2": "彼此成就。",
  "products.description":
    "从人与智能的协作，到资产与价值的流通。\n为每一层能力，打造专注的产品。",
  "products.all": "全部产品",
  "products.ai": "智能协作",
  "products.value": "价值流通",
  "products.more": "了解产品",
  "products.open": "打开产品",
  "products.layer.ai": "智能协作层",
  "products.layer.value": "价值流通层",
  "products.count": "个产品",
  "products.detail": "产品介绍",
  "products.capabilities": "核心能力",
  "linkit.role": "人与人的连接",
  "linkit.title": "连接，从对话开始。",
  "linkit.description":
    "让人、社群与智能体在同一个空间相遇。消息、通知与 Bot，把协作带到身边。",
  "linkit.detail":
    "Linkit 是生态中的沟通入口。通过个人主页、私信、群组和原生 Bot，让用户之间的交流与应用通知发生在同一个地方。",
  "linkit.f1": "个人主页与用户发现",
  "linkit.f2": "私信、群组与文件分享",
  "linkit.f3": "Bot API 与即时通知",
  "cybion.role": "智能体执行引擎",
  "cybion.title": "不止思考，更能行动。",
  "cybion.description":
    "连接模型、上下文与真实设备。让 AI 从一段对话，走向可以完成的任务。",
  "cybion.detail":
    "Cybion 提供云端 Agent 执行能力，将推理与工具执行连接起来。独立对话组织任务，Worker 将浏览器、命令行和设备操作带入工作流。",
  "cybion.f1": "独立任务与对话管理",
  "cybion.f2": "跨设备 Worker 与工具调用",
  "cybion.f3": "上下文与消息生态集成",
  "normai.role": "统一智能入口",
  "normai.title": "多种智能，一个入口。",
  "normai.description":
    "连接模型供应与应用需求。统一访问、用量审计与美元计费，让智能触手可及。",
  "normai.detail":
    "NormAI 为兼容的模型上游提供统一访问入口。按应用管理 Consumer，按调用记录用量与费用，并通过 Midas 完成统一支付结算。",
  "normai.f1": "模型访问与提供商管理",
  "normai.f2": "应用级凭据与调用审计",
  "normai.f3": "统一美元计费与 Midas 结算",
  "ctx.role": "属于你的上下文",
  "ctx.title": "让智能，真正理解你。",
  "ctx.description":
    "记录思考，组织知识，保留独有的判断。让你的上下文，成为智能的起点。",
  "ctx.detail":
    "CTX 是个人上下文的容器。以云文档与内容托管为起点，组织真正属于你的经验、知识和长期思考，为智能协作提供有深度的背景。",
  "ctx.f1": "云文档与内容托管",
  "ctx.f2": "个人知识与上下文组织",
  "ctx.f3": "面向 Agent 的上下文连接",
  "midas.role": "支付与结算",
  "midas.title": "让价值，自由流动。",
  "midas.description":
    "以美元记账，连接稳定币支付、内部转账与应用结算，构建生态的价值通道。",
  "midas.detail":
    "Midas 是移动优先的支付基础设施，以美元作为账本单位，支持 EVM 网络上的 USDC / USDT 充值与提现、内部转账，以及经用户授权的应用支付。",
  "midas.f1": "USDC / USDT 充提",
  "midas.f2": "美元账本与内部转账",
  "midas.f3": "授权支付与应用结算",
  "exchange.role": "统一资产视野",
  "exchange.title": "多个账户，一目了然。",
  "exchange.description":
    "连接不同交易所与账户来源，统一观察资产、持仓和组合，让复杂更清晰。",
  "exchange.detail":
    "1Exchange 将多交易所、远程来源与手动账户放进统一的资产视图。以一致的账户和持仓模型，组织组合账户、净值记录及 Fund 管理。",
  "exchange.f1": "多来源账户与持仓聚合",
  "exchange.f2": "组合账户与净值记录",
  "exchange.f3": "Fund 与资产管理",
  "hit.role": "人在回路的交易执行",
  "hit.title": "你的判断，精准执行。",
  "hit.description":
    "将外部目标信号交给专用执行器。凭证、参数与信号分离，让交易执行可控、可追溯。",
  "hit.detail":
    "HIT（Human-in-the-loop Trader）将外部信号转化为交易执行。由用户管理和启用执行器，连接 Binance、OKX 与 CTPD 的专用策略；HIT 本身不生成交易信号。",
  "hit.f1": "外部目标信号接入",
  "hit.f2": "交易所专用执行策略",
  "hit.f3": "人工控制与信号记录",
  "hit.risk": "实盘交易涉及资金风险。HIT 不生成信号，也不承诺任何收益。",
  "connection.eyebrow": "02 / 协同之力",
  "connection.title": "不止是产品。",
  "connection.title2": "是彼此连接的可能。",
  "connection.description":
    "每个产品专注做好一件事。\n而连接，让一个想法走得更远。",
  "connection.ai": "智能协作",
  "connection.value": "交易执行",
  "connection.ai.title": "从一次对话，到一次行动。",
  "connection.ai.description":
    "Linkit 连接人与任务，CTX 提供个人上下文，NormAI 提供智能入口，Cybion 连接工具与真实设备。",
  "connection.value.title": "从一个判断，到真实的执行。",
  "connection.value.description":
    "1Exchange 组织资产视野，HIT 承接外部目标信号，Linkit 触达执行通知。Midas 为生态提供独立的支付与结算能力。",
  "connection.note": "产品能力关系示意 · 非实时运行数据",
  "connection.hint": "点击节点，探索产品",
  "connection.label.people": "连接",
  "connection.label.context": "上下文",
  "connection.label.intelligence": "智能",
  "connection.label.action": "行动",
  "connection.label.assets": "资产",
  "connection.label.signal": "执行",
  "connection.label.message": "通知",
  "connection.label.payment": "结算",
  "about.eyebrow": "03 / 我们的理念",
  "about.title": "价值，",
  "about.title2": "在交换中发生。",
  "about.description":
    "Trade 不只是交易。\n它是想法的碰撞、能力的协作，也是价值的流动。\n我们构建工具，让每一次连接都更有意义。",
  "about.p1.title": "专注，而不孤立",
  "about.p1.body": "每个产品有清晰的边界，也有通向彼此的接口。",
  "about.p2.title": "智能，始于人",
  "about.p2.body": "技术放大人的判断与行动，而不是替代人的价值。",
  "about.p3.title": "开放，才有可能",
  "about.p3.body": "让知识、能力与价值流动起来，生长出新的可能。",
  "footer.title": "下一次连接，",
  "footer.title2": "从你开始。",
  "footer.cta": "找到你的工具",
  "footer.tagline": "构建智能与价值相连的世界。",
  "footer.products": "探索产品",
  "footer.connect": "保持连接",
  "footer.community": "Linkit 社区",
  "footer.github": "开源项目",
  "footer.back": "回到顶部",
  "footer.risk":
    "本站为产品介绍，不构成投资建议。涉及支付或交易的服务，请在使用前了解相应规则与风险。",
  "footer.copyright": "No Trade No Life. 保持连接，持续构建。",
} as const;
export type CopyKey = keyof typeof zh;
export const en: Record<CopyKey, string> = {
  "nav.ecosystem": "Ecosystem",
  "nav.connection": "Connected by design",
  "nav.about": "Our philosophy",
  "nav.explore": "Explore ecosystem",
  "nav.language": "Choose language",
  "nav.menu": "Open navigation",
  "nav.close": "Close",
  "nav.skip": "Skip to content",
  "hero.eyebrow": "BUILT FOR INTELLIGENCE. CONNECTED BY VALUE.",
  "hero.description":
    "Turn intelligence into action. Turn connection into value.\nSeven independent products. One evolving, open ecosystem.",
  "hero.cta": "Explore the ecosystem",
  "hero.secondary": "Our philosophy",
  "hero.coordinate": "INTELLIGENCE × CONNECTION × VALUE",
  "hero.scroll": "SCROLL TO EXPLORE",
  "hero.art":
    "A slowly rotating silver and green toroidal particle sculpture representing connected products",
  "hero.pause": "Pause motion",
  "hero.play": "Play motion",
  "hero.caption": "Independent by nature. Connected by design.",
  "products.eyebrow": "01 / THE ECOSYSTEM",
  "products.title": "Powerful alone.",
  "products.title2": "Better together.",
  "products.description":
    "From human–AI collaboration to the movement of value.\nPurpose-built products for every layer of possibility.",
  "products.all": "All products",
  "products.ai": "Intelligence",
  "products.value": "Value",
  "products.more": "Discover product",
  "products.open": "Open product",
  "products.layer.ai": "INTELLIGENCE LAYER",
  "products.layer.value": "VALUE LAYER",
  "products.count": "products",
  "products.detail": "Product overview",
  "products.capabilities": "CAPABILITIES",
  "linkit.role": "HUMAN CONNECTION",
  "linkit.title": "It starts with a conversation.",
  "linkit.description":
    "A shared space for people, communities, and agents. Messages, notifications, and bots bring collaboration closer.",
  "linkit.detail":
    "Linkit is the communication layer of the ecosystem. Profiles, direct messages, groups, and native bots bring human conversations and application notifications into one place.",
  "linkit.f1": "Profiles and people discovery",
  "linkit.f2": "Direct messages, groups, and files",
  "linkit.f3": "Bot API and instant notifications",
  "cybion.role": "AGENT EXECUTION",
  "cybion.title": "Beyond thought. Into action.",
  "cybion.description":
    "Connect models, context, and real devices. Take AI beyond a conversation and into work that gets done.",
  "cybion.detail":
    "Cybion provides hosted agent execution, connecting reasoning with tools. Independent conversations organize tasks, while workers bring browsers, terminals, and device operations into the workflow.",
  "cybion.f1": "Independent tasks and conversations",
  "cybion.f2": "Cross-device workers and tools",
  "cybion.f3": "Context and messaging integrations",
  "normai.role": "UNIFIED INTELLIGENCE",
  "normai.title": "Many models. One entry point.",
  "normai.description":
    "Connect model providers and applications through unified access, usage auditing, and dollar-denominated billing.",
  "normai.detail":
    "NormAI is a unified gateway for compatible model providers. Manage application-specific consumers, audit usage and costs per request, and settle payments through Midas.",
  "normai.f1": "Model access and provider management",
  "normai.f2": "App credentials and request auditing",
  "normai.f3": "USD billing and Midas settlement",
  "ctx.role": "YOUR OWN CONTEXT",
  "ctx.title": "Intelligence that knows you.",
  "ctx.description":
    "Capture your thinking, organize knowledge, and preserve your judgment. Make your context the starting point.",
  "ctx.detail":
    "CTX is a container for personal context. Starting with cloud documents and content publishing, it organizes your experience, knowledge, and long-term thinking as a foundation for intelligent collaboration.",
  "ctx.f1": "Cloud documents and publishing",
  "ctx.f2": "Personal knowledge and context",
  "ctx.f3": "Context connections for agents",
  "midas.role": "PAYMENTS & SETTLEMENT",
  "midas.title": "Value, in motion.",
  "midas.description":
    "A dollar-denominated ledger connecting stablecoin payments, internal transfers, and application settlement.",
  "midas.detail":
    "Midas is mobile-first payment infrastructure with a USD ledger. It supports USDC / USDT deposits and withdrawals on EVM networks, internal transfers, and explicitly authorized application payments.",
  "midas.f1": "USDC / USDT deposits and withdrawals",
  "midas.f2": "USD ledger and internal transfers",
  "midas.f3": "Authorized payments and settlement",
  "exchange.role": "ONE ASSET PERSPECTIVE",
  "exchange.title": "Many accounts. One clear view.",
  "exchange.description":
    "Connect exchanges and account sources. See assets, positions, and portfolios through one consistent perspective.",
  "exchange.detail":
    "1Exchange brings exchanges, remote sources, and manual accounts into one asset view. Consistent account and position models support composite accounts, equity history, and fund management.",
  "exchange.f1": "Multi-source accounts and positions",
  "exchange.f2": "Composite accounts and equity history",
  "exchange.f3": "Fund and asset management",
  "hit.role": "HUMAN-IN-THE-LOOP TRADER",
  "hit.title": "Your judgment. Precise execution.",
  "hit.description":
    "Turn external target signals into execution. Separate credentials, parameters, and signals to keep humans in control.",
  "hit.detail":
    "HIT turns external target signals into trade execution. Users control and enable dedicated strategies for Binance, OKX, and CTPD. HIT does not generate trading signals itself.",
  "hit.f1": "External target-signal API",
  "hit.f2": "Exchange-specific execution strategies",
  "hit.f3": "Human control and signal history",
  "hit.risk":
    "Live trading involves financial risk. HIT does not generate signals or guarantee returns.",
  "connection.eyebrow": "02 / CONNECTED BY DESIGN",
  "connection.title": "More than products.",
  "connection.title2": "A world of connections.",
  "connection.description":
    "Each product does one thing with purpose.\nConnections take your ideas further.",
  "connection.ai": "Intelligence workflow",
  "connection.value": "Trading workflow",
  "connection.ai.title": "From a conversation to an action.",
  "connection.ai.description":
    "Linkit connects people and tasks. CTX supplies personal context. NormAI provides intelligence, and Cybion connects tools with real devices.",
  "connection.value.title": "From a decision to real execution.",
  "connection.value.description":
    "1Exchange organizes asset visibility. HIT accepts external target signals. Linkit delivers notifications. Midas independently provides payments and settlement across the ecosystem.",
  "connection.note": "CAPABILITY MAP · NOT LIVE TELEMETRY",
  "connection.hint": "Select a node to explore",
  "connection.label.people": "CONNECT",
  "connection.label.context": "CONTEXT",
  "connection.label.intelligence": "THINK",
  "connection.label.action": "ACT",
  "connection.label.assets": "OBSERVE",
  "connection.label.signal": "EXECUTE",
  "connection.label.message": "NOTIFY",
  "connection.label.payment": "SETTLE",
  "about.eyebrow": "03 / OUR PHILOSOPHY",
  "about.title": "Value happens",
  "about.title2": "in exchange.",
  "about.description":
    "Trade is more than a transaction.\nIt is the exchange of ideas, the collaboration of capabilities, and the movement of value.\nWe build tools that make every connection count.",
  "about.p1.title": "Focused, not isolated",
  "about.p1.body":
    "Clear boundaries for every product. Open interfaces between them.",
  "about.p2.title": "Intelligence starts with people",
  "about.p2.body":
    "Technology amplifies human judgment and action—not human replacement.",
  "about.p3.title": "Open to possibility",
  "about.p3.body":
    "When knowledge, capabilities, and value move, new possibilities emerge.",
  "footer.title": "Your next connection",
  "footer.title2": "starts here.",
  "footer.cta": "Find your tools",
  "footer.tagline": "Connecting intelligence with value.",
  "footer.products": "EXPLORE",
  "footer.connect": "CONNECT",
  "footer.community": "Linkit community",
  "footer.github": "Open source",
  "footer.back": "Back to top",
  "footer.risk":
    "This website introduces products and is not investment advice. Understand the applicable terms and risks before using payment or trading services.",
  "footer.copyright": "No Trade No Life. Stay connected. Keep building.",
};
export const dictionaries = { zh, en };
